// Success Stories - Real American men sharing their personal journeys
const initialReviews = [
    {
        id: 1,
        reviewerName: "Michael R.",
        age: "48",
        location: "Dallas, TX",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "I had been struggling with ED for three years. It was killing my marriage and my self-esteem. I was too embarrassed to talk to my regular doctor, so I kept putting it off. Then a buddy mentioned Sarah. Man, I'm so glad I reached out. She didn't make me feel awkward at all - just listened and asked the right questions. She set me up with Viagra and explained exactly how to use it. First time I tried it, I felt like my old self again. My wife and I are closer than we've been in years. Sarah checks in on me regularly too, which means a lot.",
        date: "03/15/2025",
        effect: "Complete Recovery",
        usageTime: "3 months with Sarah",
        featured: true
    },
    {
        id: 2,
        reviewerName: "James T.",
        age: "52",
        location: "Atlanta, GA",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "I'll be honest - I was skeptical about reaching out to someone online. But I was desperate. My relationship with my girlfriend was on the rocks because I couldn't perform. Sarah was incredibly patient. She didn't push anything on me, just explained my options. We started with half a dose to see how my body reacted. No side effects, and the results were amazing. My confidence is through the roof now. I'm actually dating again, feeling like I'm in my 30s.",
        date: "03/22/2025",
        effect: "Major Improvement",
        usageTime: "2 months with Sarah",
        featured: true
    },
    {
        id: 3,
        reviewerName: "David K.",
        age: "45",
        location: "Phoenix, AZ",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "The thing about ED that nobody talks about is how it messes with your head. I was avoiding intimacy, making excuses, feeling like less of a man. My wife thought I wasn't attracted to her anymore. Sarah understood all of that. She recommended Cialis because I told her I didn't want to 'plan' everything. Now I just take it Friday evening and I'm good for the whole weekend. Feels natural, not forced. Sarah really gets it.",
        date: "04/08/2025",
        effect: "Complete Recovery",
        usageTime: "4 months with Sarah",
        featured: true
    },
    {
        id: 4,
        reviewerName: "Robert M.",
        age: "50",
        location: "Denver, CO",
        avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "I'm a pretty frugal guy, so I was worried about the cost. Sarah actually listened to my budget concerns and suggested a generic option that was way more affordable than I expected. She explained the differences, the pros and cons, never pressured me into the expensive stuff. I've been using it for two months now and honestly, I can't tell the difference from the brand name stuff I tried before. Sarah treats you like a person, not a paycheck.",
        date: "04/17/2025",
        effect: "Significant Improvement",
        usageTime: "2 months with Sarah",
        featured: true
    },
    {
        id: 5,
        reviewerName: "Chris B.",
        age: "38",
        location: "Miami, FL",
        avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "I had two problems - couldn't get hard AND couldn't last. I was thinking I'd need two different medications. Sarah suggested this dual-action pill instead. Let me tell you, this stuff is incredible. I went from barely 2 minutes to lasting 20+ minutes, and I'm rock solid the whole time. My girlfriend's reaction the first time... priceless. She literally said 'what happened to you?' Sarah saved me money AND fixed both issues at once.",
        date: "05/03/2025",
        effect: "Complete Recovery",
        usageTime: "2 months with Sarah",
        featured: true
    },
    {
        id: 6,
        reviewerName: "Jason P.",
        age: "42",
        location: "Seattle, WA",
        avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "A friend recommended Sarah after I complained about my 'performance issues' during a fishing trip. I was embarrassed even talking to him, but he swore by her. Best decision I made. Sarah asked detailed questions about my lifestyle, my health, even my diet. She didn't just throw pills at me - she actually created a plan. The follow-up care is what surprised me most. She actually remembers our conversations and adjusts things based on how I'm doing.",
        date: "05/19/2025",
        effect: "Major Results",
        usageTime: "3 months with Sarah",
        featured: true
    },
    {
        id: 7,
        reviewerName: "William H.",
        age: "60",
        location: "Chicago, IL",
        avatar: "https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Divorced for 5 years, finally met someone special. The thought of disappointing her terrified me. I almost called off our relationship before it started. Sarah was so understanding - she didn't treat me like an old man, just a guy who needed help. She was careful about my health history, made sure my heart was good before prescribing anything. First time with my new lady... everything worked perfectly. We're talking about moving in together now. Sarah gave me my second chance at love.",
        date: "06/02/2025",
        effect: "Complete Recovery",
        usageTime: "4 months with Sarah",
        featured: true
    },
    {
        id: 8,
        reviewerName: "Thomas S.",
        age: "55",
        location: "Boston, MA",
        avatar: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Type 2 diabetic here. I'd been told ED was just something I had to live with. My wife had basically accepted that part of our marriage was over. Sarah was different - she asked about my diabetes, my medications, even sent me for a heart check before we started. She was cautious and thorough. Now? Let's just say my wife is very happy, and so am I. Sarah knows her stuff and actually cares about your safety.",
        date: "06/14/2025",
        effect: "Significant Improvement",
        usageTime: "3 months with Sarah",
        featured: true
    },
    {
        id: 9,
        reviewerName: "Daniel L.",
        age: "47",
        location: "Portland, OR",
        avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "20 years of marriage, and things had gotten... routine. Then they stopped working entirely. The pressure was crushing me. Sarah didn't try to sell me the most expensive stuff. She actually recommended something affordable and appropriate for my situation. Two months in, my wife and I are like newlyweds again. Sarah even gave me tips on overall health - diet, exercise, stress management. She treats the whole person.",
        date: "06/28/2025",
        effect: "Complete Recovery",
        usageTime: "2 months with Sarah",
        featured: true
    },
    {
        id: 10,
        reviewerName: "Matthew C.",
        age: "35",
        location: "Austin, TX",
        avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Startup life destroyed my health - 80-hour weeks, constant stress, terrible diet. By 35, I had the sex drive of a 70-year-old. My girlfriend was understanding, but I knew it was killing our relationship. Sarah created a whole wellness plan, not just meds. She checks in to make sure I'm sleeping better, managing stress. The change has been incredible - in bed AND in my energy levels at work. I'm evangelizing about Sarah to all my founder friends.",
        date: "07/11/2025",
        effect: "Complete Recovery",
        usageTime: "3 months with Sarah",
        featured: true
    },
    {
        id: 11,
        reviewerName: "Anthony G.",
        age: "43",
        location: "Las Vegas, NV",
        avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "First time ever consulting about this stuff online. I was awkward as hell, stumbling over my words. Sarah made it comfortable. She has this way of talking about everything matter-of-factly, no judgment. She explained dosage timing, what to expect, what to avoid. I've been using her recommendations for two months now, and every single time has been successful. My confidence is back, and I'm actually enjoying dating again.",
        date: "07/24/2025",
        effect: "Major Improvement",
        usageTime: "2 months with Sarah",
        featured: false
    },
    {
        id: 12,
        reviewerName: "Kevin W.",
        age: "49",
        location: "San Diego, CA",
        avatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "I'd tried ordering stuff online before - sketchy websites, questionable pills, inconsistent results. Sarah was completely different. Professional, licensed, actually knew what she was talking about. She switched me to a different medication that works better for my body, adjusted the timing, and now it's smooth sailing every time. The difference between some random internet pharmacy and an actual medical professional is huge.",
        date: "08/05/2025",
        effect: "Excellent Results",
        usageTime: "1 month with Sarah",
        featured: false
    },
    {
        id: 13,
        reviewerName: "Brian N.",
        age: "40",
        location: "New York, NY",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "My girlfriend was getting frustrated with our sex life - or lack thereof. I was avoiding intimacy, making excuses about being tired. The truth was I couldn't perform and didn't know what to do. Sarah was reassuring. She said this was fixable, gave me a specific plan. First time after starting treatment, I lasted 15 minutes. My girlfriend was shocked - in a good way. Our relationship is stronger than ever. Sarah literally saved us.",
        date: "08/18/2025",
        effect: "Complete Recovery",
        usageTime: "2 months with Sarah",
        featured: true
    },
    {
        id: 14,
        reviewerName: "Steven D.",
        age: "58",
        location: "Nashville, TN",
        avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Thought my sex life was over at my age. My son actually convinced me to contact Sarah - he was worried about me being alone. Sarah explained how the medicine works, that age isn't the barrier I thought it was. She was respectful, never made me feel old or embarrassed. Now I'm dating again, keeping up with women 10 years younger than me. Feels incredible to have that part of my life back. Thanks to Sarah and my son's push.",
        date: "09/01/2025",
        effect: "Significant Improvement",
        usageTime: "4 months with Sarah",
        featured: true
    },
    {
        id: 15,
        reviewerName: "Mark F.",
        age: "46",
        location: "Houston, TX",
        avatar: "https://images.unsplash.com/photo-1542596594-649edbc13630?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "I'm a truck driver, on the road constantly. Regular meds were hard to time right with my crazy schedule. Sarah understood my lifestyle immediately. She recommended something longer-lasting so I didn't have to plan everything precisely. Works perfectly for my unpredictable schedule. She even texts me reminders when she knows I'm on a long haul. That's the kind of personal attention you don't expect.",
        date: "09/14/2025",
        effect: "Working Great",
        usageTime: "3 months with Sarah",
        featured: false
    },
    {
        id: 16,
        reviewerName: "Eric J.",
        age: "37",
        location: "Los Angeles, CA",
        avatar: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Newly married and already having problems in the bedroom. The pressure was intense - new wife, expectations, plus my own anxiety. Sarah was quick to respond, understood the urgency of my situation. First time using her recommendations was our honeymoon all over again. Six months later, we're still going strong. I credit Sarah with giving my marriage the start it deserved.",
        date: "09/27/2025",
        effect: "Complete Recovery",
        usageTime: "6 months with Sarah",
        featured: true
    },
    {
        id: 17,
        reviewerName: "Ryan P.",
        age: "51",
        location: "Philadelphia, PA",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "High blood pressure and ED is a scary combination. I'd been afraid to try anything because of my heart. Sarah took the time to review ALL my medications, consulted with me about timing and safety. She was more thorough than my own doctor. Three months in, my blood pressure is stable AND my ED is handled. She coordinated with my cardiologist to make sure everything was safe. That's real professionalism.",
        date: "10/08/2025",
        effect: "Significant Improvement",
        usageTime: "3 months with Sarah",
        featured: false
    },
    {
        id: 18,
        reviewerName: "Jeffrey A.",
        age: "44",
        location: "Charlotte, NC",
        avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Second marriage, and I was terrified of screwing it up. My first marriage ended partly because of intimacy issues I never addressed. Didn't want to repeat that pattern. Sarah did a full consultation, recommended exactly what I needed. My new wife has no idea I ever had a problem - she thinks I'm just naturally this way. Sarah's discretion and effectiveness gave me a fresh start.",
        date: "10/22/2025",
        effect: "Complete Recovery",
        usageTime: "2 months with Sarah",
        featured: true
    },
    {
        id: 19,
        reviewerName: "Andrew S.",
        age: "41",
        location: "Detroit, MI",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "I'd tried pills before, supplements, even those sketchy online remedies. Nothing worked. I was ready to give up, accept this was my life now. Sarah was my last try. She explained why those other things failed and how her approach was different. She was right. For the first time in years, everything works like it should. I'm telling every guy I know who's struggling - call Sarah.",
        date: "11/04/2025",
        effect: "Complete Recovery",
        usageTime: "4 months with Sarah",
        featured: true
    },
    {
        id: 20,
        reviewerName: "Timothy R.",
        age: "56",
        location: "San Francisco, CA",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Prostate surgery at 54 left me with ED. My urologist said it might improve, might not. It didn't. I was depressed, felt like half a man. Sarah connected with my surgeon to understand my specific situation, then created a careful, gradual treatment plan. Started low and slow. Now, two years post-surgery, my wife and I are intimate again. It's different than before, but it's good. Sarah never gave up on me when I was ready to give up on myself.",
        date: "11/17/2025",
        effect: "Significant Improvement",
        usageTime: "5 months with Sarah",
        featured: true
    },
    {
        id: 21,
        reviewerName: "Richard K.",
        age: "53",
        location: "Phoenix, AZ",
        avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "My doctor basically shrugged when I mentioned my ED. Said it happens with age. Sarah didn't accept that. She ran through my entire health profile, found my testosterone was low, and created a comprehensive plan. Six months later, I feel 10 years younger. It's not just the pills - it's the whole approach she takes. She actually cares about fixing the problem, not just masking it.",
        date: "12/01/2025",
        effect: "Complete Recovery",
        usageTime: "6 months with Sarah",
        featured: true
    },
    {
        id: 22,
        reviewerName: "Brandon M.",
        age: "36",
        location: "Denver, CO",
        avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Performance anxiety was killing me. Every time I got close to intimacy, I'd panic. Sarah recognized it was psychological as much as physical. She recommended a low-dose daily approach that took the pressure off. No more planning, no more anxiety. Now when the moment happens, I'm ready. Sarah understood it wasn't just about the mechanics - it was about my confidence.",
        date: "12/12/2025",
        effect: "Complete Recovery",
        usageTime: "3 months with Sarah",
        featured: true
    },
    {
        id: 23,
        reviewerName: "Patrick O.",
        age: "49",
        location: "Boston, MA",
        avatar: "https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Widowed at 45, started dating again at 48. Terrified doesn't begin to describe it. Sarah was like a coach and a doctor combined. She prepared me for the physical AND emotional aspects of being intimate with someone new. Her support gave me courage to pursue a wonderful woman. We're engaged now. I never thought I'd find love again, and I never thought I'd perform like this again either.",
        date: "12/23/2025",
        effect: "Complete Recovery",
        usageTime: "4 months with Sarah",
        featured: true
    },
    {
        id: 24,
        reviewerName: "Gregory H.",
        age: "61",
        location: "Miami, FL",
        avatar: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Retired and divorced, thought my best years were behind me. Met someone at my golf club and panicked about the bedroom situation. Sarah didn't treat me like an old guy - she treated me like a man who wanted to enjoy his golden years. Now I'm keeping up with a woman 15 years younger. My golf buddies are asking what my secret is. Sarah gave me my swagger back.",
        date: "01/05/2026",
        effect: "Major Improvement",
        usageTime: "3 months with Sarah",
        featured: false
    },
    {
        id: 25,
        reviewerName: "Joshua L.",
        age: "34",
        location: "Seattle, WA",
        avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Porn addiction wrecked my ability to perform with real women. It was embarrassing and isolating. Sarah didn't judge me - she understood the neuroscience behind it. She helped me understand what was happening to my brain AND my body. With her treatment plan and some lifestyle changes she suggested, I'm having the best sex of my life with my girlfriend. Real connection, real intimacy. Sarah helped save me from myself.",
        date: "01/14/2026",
        effect: "Complete Recovery",
        usageTime: "5 months with Sarah",
        featured: true
    },
    {
        id: 26,
        reviewerName: "Scott B.",
        age: "47",
        location: "Chicago, IL",
        avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Chemotherapy for lymphoma saved my life but killed my sex life. My oncologist said to 'give it time.' Two years later, nothing. Sarah understood the specific challenges of post-chemo ED. She was patient as we tried different approaches, adjusted dosages, found what worked for my compromised system. Slowly but surely, things came back online. My wife cried the first time everything worked. So did I.",
        date: "01/22/2026",
        effect: "Significant Improvement",
        usageTime: "8 months with Sarah",
        featured: true
    },
    {
        id: 27,
        reviewerName: "Derek W.",
        age: "39",
        location: "Austin, TX",
        avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "COVID long-hauler here. Among the many lingering symptoms was ED. My regular doctors were focused on my lungs and heart, ignoring this side effect. Sarah took it seriously. She researched how COVID affects vascular health and tailored her approach accordingly. It took longer than typical cases, but she stuck with me. Eight months later, I'm basically back to normal. Sarah never made me feel like my case was too complicated.",
        date: "02/03/2026",
        effect: "Complete Recovery",
        usageTime: "8 months with Sarah",
        featured: true
    },
    {
        id: 28,
        reviewerName: "Raymond C.",
        age: "57",
        location: "Atlanta, GA",
        avatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Heart attack at 54, got the all-clear for sexual activity but was terrified. What if my heart couldn't handle it? Sarah worked directly with my cardiologist to establish safe parameters. She started me on the lowest possible dose, monitored my blood pressure, taught me warning signs to watch for. Now I'm confident and active again without constant fear. Sarah gave me back my life AND my peace of mind.",
        date: "02/14/2026",
        effect: "Complete Recovery",
        usageTime: "6 months with Sarah",
        featured: true
    },
    {
        id: 29,
        reviewerName: "Benjamin T.",
        age: "44",
        location: "Dallas, TX",
        avatar: "https://images.unsplash.com/photo-1542596594-649edbc13630?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Low testosterone plus ED - double whammy. Previous doctor just wanted to give me injections and call it a day. Sarah looked at the big picture. She coordinated with an endocrinologist, adjusted my TRT protocol, AND addressed the ED specifically. The synergy was incredible. I'm not just functional in bed - I'm killing it at work, in the gym, everywhere. Total life transformation that started with one message to Sarah.",
        date: "02/28/2026",
        effect: "Complete Recovery",
        usageTime: "7 months with Sarah",
        featured: true
    },
    {
        id: 30,
        reviewerName: "Nathan G.",
        age: "42",
        location: "San Diego, CA",
        avatar: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "After my divorce, I thought I'd never date again. Not because I didn't want to, but because I was terrified of the bedroom. Two years of a sexless marriage had destroyed my confidence. Sarah was the first person who made me feel like this was a medical issue, not a character flaw. She explained the physiology, set realistic expectations, and celebrated every small win with me. Six months later, I'm dating a wonderful woman and feeling like myself again.",
        date: "03/08/2025",
        effect: "Complete Recovery",
        usageTime: "6 months with Sarah",
        featured: true
    },
    {
        id: 31,
        reviewerName: "Kenneth M.",
        age: "51",
        location: "Portland, OR",
        avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "I'm a firefighter, always prided myself on being strong and capable. When ED hit, it hit my identity hard. I couldn't talk to the guys at the station about it. Sarah understood that pride piece - she didn't make me feel weak for needing help. Instead, she framed it as taking charge of my health like I do with my fitness. Now I'm back to full strength in every way. Even told one of my buddies about her - he called to thank me last week.",
        date: "03/25/2025",
        effect: "Complete Recovery",
        usageTime: "4 months with Sarah",
        featured: true
    },
    {
        id: 32,
        reviewerName: "Samuel P.",
        age: "46",
        location: "Nashville, TN",
        avatar: "https://images.unsplash.com/photo-1573007974656-b958089e9f7b?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Being a pastor, I felt immense shame about my ED. I thought God was punishing me, or that I was failing as a husband. Sarah approached everything with such compassion and zero judgment. She helped me see that seeking treatment was actually caring for my wife and my marriage. The medication worked, but her spiritual sensitivity meant even more. My wife and I are closer than ever, and I can focus on my ministry again without this burden.",
        date: "04/02/2025",
        effect: "Complete Recovery",
        usageTime: "3 months with Sarah",
        featured: true
    },
    {
        id: 33,
        reviewerName: "Edward L.",
        age: "59",
        location: "Las Vegas, NV",
        avatar: "https://images.unsplash.com/photo-1542178243-bc20204b769f?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "I manage a casino, work crazy hours, high stress environment. Started having issues in my early 50s but ignored it. By 59, my girlfriend of two years was talking about leaving. Sarah was direct - no BS, which I appreciated. She cut through my excuses and gave me a plan that worked with my schedule. The confidence came back, then the performance. My girlfriend stayed, and we're talking about getting married. Sarah quite literally saved my relationship.",
        date: "04/19/2025",
        effect: "Significant Improvement",
        usageTime: "5 months with Sarah",
        featured: true
    },
    {
        id: 34,
        reviewerName: "Christian R.",
        age: "33",
        location: "New York, NY",
        avatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "I'm young, fit, eat clean - ED wasn't supposed to happen to me. When it did, I went into denial. Made excuses, blamed stress, kept telling myself it would get better. It didn't. Sarah was the wake-up call I needed. She ran some tests, found some hormonal imbalances I never knew about, and got me on the right track. At 33, I feel like I've got my whole life back ahead of me. Don't wait like I did - just call her.",
        date: "05/01/2025",
        effect: "Complete Recovery",
        usageTime: "3 months with Sarah",
        featured: true
    },
    {
        id: 35,
        reviewerName: "Peter W.",
        age: "62",
        location: "Scottsdale, AZ",
        avatar: "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Retired early, bought a boat, planned to enjoy life. Then my wife left me - partly because our sex life had died years ago and I never addressed it. Alone on that boat, I realized I'd made a terrible mistake ignoring my health. Sarah helped me understand it's never too late. At 62, I'm dating again, keeping up with women my age and younger. Just got engaged to an amazing woman. Sarah gave me the tools to not repeat my mistakes.",
        date: "05/17/2025",
        effect: "Major Improvement",
        usageTime: "6 months with Sarah",
        featured: true
    },
    {
        id: 36,
        reviewerName: "Keith A.",
        age: "41",
        location: "Raleigh, NC",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "My wife and I were trying for our second child, but I couldn't perform on demand. The pressure was crushing - ovulation calendars, scheduled sex, and me failing every time. Sarah understood the fertility timing pressure immediately. She set me up with something that worked fast and reliably. Two months later, we conceived. Our daughter is 3 months old now. Sarah didn't just fix my ED - she helped create my baby girl.",
        date: "05/29/2025",
        effect: "Complete Recovery",
        usageTime: "2 months with Sarah",
        featured: true
    },
    {
        id: 37,
        reviewerName: "Philip H.",
        age: "54",
        location: "Indianapolis, IN",
        avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Veteran with PTSD. The medications the VA gave me helped my flashbacks but killed my sex drive. My wife was understanding at first, but after three years, I could see the strain. Sarah worked around my existing meds, found something that didn't interact badly. More importantly, she understood the military mindset - no pity, just solutions. I'm functioning again, feeling like a whole man. My wife cried when I told her about Sarah.",
        date: "06/06/2025",
        effect: "Significant Improvement",
        usageTime: "4 months with Sarah",
        featured: true
    },
    {
        id: 38,
        reviewerName: "Roger D.",
        age: "49",
        location: "Kansas City, MO",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Family business, three kids in college, aging parents - stress was my constant companion. ED was just another symptom of my life spiraling. Sarah didn't just write a prescription. She asked about my sleep, my exercise, my stress management. She treated the whole picture. Six months later, I'm not just better in bed - I'm better at everything. My kids noticed the difference in my energy. Sarah's approach changed my entire life trajectory.",
        date: "06/21/2025",
        effect: "Complete Recovery",
        usageTime: "6 months with Sarah",
        featured: true
    },
    {
        id: 39,
        reviewerName: "Lawrence M.",
        age: "45",
        location: "Salt Lake City, UT",
        avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "Mormon, married young, never been with anyone but my wife. When ED hit at 44, I felt broken in ways I couldn't explain to anyone in my community. Sarah provided a safe, confidential space where I could be completely honest. She respected my values while giving me real medical help. My marriage is stronger now than it's been in years. Sarah understood that for me, this wasn't just about sex - it was about my entire identity as a husband.",
        date: "07/07/2025",
        effect: "Complete Recovery",
        usageTime: "4 months with Sarah",
        featured: true
    },
    {
        id: 40,
        reviewerName: "Alan K.",
        age: "50",
        location: "Minneapolis, MN",
        avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&h=100&fit=crop&crop=face",
        rating: 5,
        content: "My twin brother died of a heart attack at 48. When I started having ED symptoms, I ignored them, fearing it meant my heart was bad too. Sarah was the first person to explain the connection between cardiovascular health and ED in a way that didn't terrify me. She sent me for proper cardiac testing, got me cleared, then treated the ED. Turns out it was mostly psychological - grief and fear. Sarah helped me process that and heal. I'm 50 and healthier than I've been in years.",
        date: "07/19/2025",
        effect: "Complete Recovery",
        usageTime: "5 months with Sarah",
        featured: true
    }
];

// Data Manager
const DataManager = {
    getReviews() {
        return initialReviews;
    },

    getFeaturedReviews(limit = 40) {
        return initialReviews.filter(r => r.featured).slice(0, limit);
    },

    getStats() {
        return {
            totalReviews: '10000+',
            verifiedClients: '10000+',
            successRate: 99
        };
    },

    initData() {
        console.log('Data initialized:', initialReviews.length, 'reviews');
    }
};
